---
- name: "Install lirc 10.1"
  # Installs and configures lirc, verified under kernel 5.4.51+ and lirc 0.10.1-6.2~deb10u1

  hosts: all


  handlers:
    - name: restart lircd
      systemd:
        name: lircd
        state: restarted
      become: yes

  tasks:
    - name: Enable dtoverlays for lirc
      lineinfile:
        path: /boot/config.txt
        regexp: "{{ item.regexp }}"
        line: "{{ item.line }}"
      with_items:
        - regexp: '.*dtoverlay=gpio-ir,.*'
          line: 'dtoverlay=gpio-ir,gpio_pin=17'
        # gpio-ir-tx is standard overlay, but may not work well with raw codes
        - regexp: '.*dtoverlay=.*-ir-tx,.*'
          line: 'dtoverlay=gpio-ir-tx,gpio_pin=18'
        # If using raw codes in a remote file, use pwm-ir-tx instead of gpio-ir-tx
        # - regexp: '.*dtoverlay=.*-ir-tx,.*'
        #   line: 'dtoverlay=pwm-ir-tx,gpio_pin=18'
      become: yes


    - name: Install lirc
      apt:
        name: lirc
        state: latest
        update_cache: yes
      become: yes


    - name: Configure lirc_options.conf file
      lineinfile:
        path: /etc/lirc/lirc_options.conf
        regexp: "{{ item.regexp }}"
        line: "{{ item.line}}"
      with_items:
        - regexp: '^device'
          line: 'device          = /dev/lirc0'
        - regexp: '^driver'
          line: 'driver          = default'
      notify: restart lircd
      become: yes


    - name: Disabling original devinput.lircd.conf file using devinput
      command: mv /etc/lirc/lircd.conf.d/devinput.lircd.conf /etc/lirc/lircd.conf.d/devinput.lircd.dist
