---
- name: "Add configuration files for ha-bridge and remote files"
  hosts: localhost
  gather_facts: no

  tasks:
    - name: Update all apt packages
      apt:
        name: "*"
        state: latest
        force_apt_get: yes
        update_cache: yes
      become: yes

    # - name: Copy remote configuration files
    #   copy:
    #     src: files/remotes/
    #     dest: /etc/lirc/lircd.conf.d/
    #     force: no
    #   become: yes

    - name: Copy ir-ctl raw IR files
      # Recorded using the following command
      # ir-ctl -rSpectrafire_KEY_POWER.raw -m -w -1 -d /dev/lirc1
      copy:
        src: files/ir-ctl-raw
        dest: /usr/local/ha-bridge/data
        force: no
      become: yes

    - name: Copy ha-bridge backup and supporting files
      copy:
        src: habridge/backup/
        dest: /usr/local/ha-bridge/data
        force: no
      become: yes
